<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MacroRecorder.Core\MacroRecorder.Core.csproj" />
    <ProjectReference Include="..\MacroRecorder.Input\MacroRecorder.Input.csproj" />
  </ItemGroup>
</Project>
